package com.github.astat1cc.vinylore

object Consts {

    const val PREPARE_MEDIA_ACTION = "START_MEDIA_PLAY_ACTION"
    const val RESUME_MEDIA_PLAY_ACTION = "RESUME_MEDIA_PLAY_ACTION"
    const val PAUSE_MEDIA_PLAY_ACTION = "PAUSE_MEDIA_PLAY_ACTION"
    const val START_CRACKLE_ACTION = "START_CRACKLE_ACTION"
    const val START_TRACK_PLAYING_ACTION = "START_TRACK_PLAYING_ACTION"
    const val REFRESH_MEDIA_PLAY_ACTION = "REFRESH_MEDIA_PLAY_ACTION"
    const val PLAYBACK_UPDATE_INTERVAL = 1000L
    const val MY_MEDIA_ROOT_ID = "media_root_id"
}