package com.github.astat1cc.vinylore.core

object AppConst {

    const val PLAYING_ALBUM_PATH_KEY = "PLAYING_ALBUM_PATH_KEY"
    const val CHOSEN_ROOT_DIRECTORY_PATH_KEY = "CHOSEN_DIRECTORY_PATH_KEY"
    const val LAST_SCAN_DATE_KEY = "LAST_SCAN_DATE_KEY"

    const val SLIDE_IN_DURATION = 350
    const val SLIDE_OUT_DURATION = 300

    const val VINYL_TRACK_START_TONEARM_ROTATION = 19f
    const val VINYL_TRACK_START_TONEARM_ROTATION_FOR_ANIMATABLE = 1900f


    const val VINYL_STARTING_ANIMATION_DURATION = 1000
    const val VINYL_VISIBILITY_SHRINK_OUT_DURATION = 220
    const val TONEARM_MOVING_FROM_DISC_TO_START_POSITION_DURATION = 380
    const val DELAY_AFTER_SKIPPING_BEFORE_SHOWING_VINYL = 100L
    const val FADE_OUT_DURATION = 200

}